# Generated by Django 5.2 on 2025-04-24 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterModelOptions(
            name="travel",
            options={
                "verbose_name": "Путешествие",
                "verbose_name_plural": "Путешествия",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="description",
            field=models.TextField(verbose_name="Описание комментария"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="travel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="travel.travel",
                verbose_name="Путешествие",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=63, verbose_name="Название тега"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="description",
            field=models.TextField(verbose_name="Описание путешествия"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="travels/images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичность"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Местоположение"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="tags",
            field=models.ManyToManyField(
                related_name="travels", to="travel.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название путешествия"),
        ),
        migrations.AlterField(
            model_name="travel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
