# Generated by Django 5.2 on 2025-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0002_alter_comment_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="travel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
